// <auto-generated />
using CompletemtgDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(mtgDbContext))]
    [Migration("20251126165727_AddArraysSetTimeStamp")]
    partial class AddArraysSetTimeStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompletemtgDatabase.BoosterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoostersTotalWeight")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SourceSetCodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoosterConfig");
                });

            modelBuilder.Entity("CompletemtgDatabase.BoosterPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoosterConfigId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoosterConfigId");

                    b.ToTable("BoosterPack");
                });

            modelBuilder.Entity("CompletemtgDatabase.BoosterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowDuplicates")
                        .HasColumnType("bit");

                    b.Property<bool?>("BalanceColors")
                        .HasColumnType("bit");

                    b.Property<bool?>("Fixed")
                        .HasColumnType("bit");

                    b.Property<bool>("Foil")
                        .HasColumnType("bit");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BoosterSheet");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ArtistIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsciiName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AttractionLights")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("BoosterTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CardParts")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuelDeck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EdhrecRank")
                        .HasColumnType("int");

                    b.Property<double?>("EdhrecSaltiness")
                        .HasColumnType("float");

                    b.Property<string>("FaceFlavorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FaceManaValue")
                        .HasColumnType("float");

                    b.Property<string>("FaceName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Finishes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FrameEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAlternativeDeckLimit")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasContentWarning")
                        .HasColumnType("bit");

                    b.Property<int>("IdentifiersId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAlternative")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFullArt")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFunny")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGameChanger")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnlineOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOversized")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPromo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRebalanced")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReprint")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStorySpotlight")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTextless")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTimeshifted")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadershipSkillsId")
                        .HasColumnType("int");

                    b.Property<int>("LegalitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Life")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loyalty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OriginalPrintings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalType")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OtherFaceIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Printings")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PromoTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaceUrlsId")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SetId")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Types")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Variations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Watermark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentifiersId");

                    b.HasIndex("LeadershipSkillsId");

                    b.HasIndex("LegalitiesId");

                    b.HasIndex("PurchaceUrlsId");

                    b.HasIndex("SetId");

                    b.HasIndex("SourceProductsId");

                    b.ToTable("CardSet");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardSetDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("DeckSetId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckSetId1")
                        .HasColumnType("int");

                    b.Property<int?>("DeckSetId2")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeckSetId");

                    b.HasIndex("DeckSetId1");

                    b.HasIndex("DeckSetId2");

                    b.ToTable("CardSetDeck");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ArtistIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsciiName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("BoosterTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CardParts")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EdhrecSaltiness")
                        .HasColumnType("float");

                    b.Property<string>("FaceFlavorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Finishes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FrameEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("HasNonFoil")
                        .HasColumnType("bit");

                    b.Property<int>("IdentifiersId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFullArt")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFunny")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnlineOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOversized")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPromo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReprint")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTextless")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loyalty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalType")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OtherFaceIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PromoTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedCardsId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ReverseRelated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SourceProducts")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Subsets")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Subtypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Supertypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Types")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Watermark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentifiersId");

                    b.HasIndex("RelatedCardsId");

                    b.ToTable("CardToken");
                });

            modelBuilder.Entity("CompletemtgDatabase.DeckSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SealedProductUuids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeckSet");
                });

            modelBuilder.Entity("CompletemtgDatabase.ForeignData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardSetId")
                        .HasColumnType("int");

                    b.Property<string>("FaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentifiersId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("IdentifiersId");

                    b.ToTable("ForeignData");
                });

            modelBuilder.Entity("CompletemtgDatabase.Identifiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardKingdomEtchedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardKingdomFoilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardKingdomId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardsphereFoilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardsphereId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardtraderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McmMetaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniaturemarketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgArenaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgjsonFoilVersionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgjsonNonFoilVersionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgjsonV4Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgoFoilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiverseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallCardBackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallIllustrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallOracleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerEtchedProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TntId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("CompletemtgDatabase.LeadershipSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("brawl")
                        .HasColumnType("bit");

                    b.Property<bool>("commander")
                        .HasColumnType("bit");

                    b.Property<bool>("oatherbreaker")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LeadershipSkills");
                });

            modelBuilder.Entity("CompletemtgDatabase.Legalities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alchemy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commander")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explorer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Future")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gladiator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historicbrawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oathbreaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oldschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pauper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paupercommander")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pioneer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premodern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standardbrawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timeless")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vintage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Legalities");
                });

            modelBuilder.Entity("CompletemtgDatabase.PurchaceUrls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardKingdom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardKingdomEtched")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardKingdomFoil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cardmarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tcgplayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerEtched")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaceUrls");
                });

            modelBuilder.Entity("CompletemtgDatabase.RelatedCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("reverseRelated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RelatedCards");
                });

            modelBuilder.Entity("CompletemtgDatabase.Rulings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardCount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContentsId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifiersId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductSize")
                        .HasColumnType("int");

                    b.Property<int>("PurchaceUrlsId")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentsId");

                    b.HasIndex("IdentifiersId");

                    b.HasIndex("PurchaceUrlsId");

                    b.ToTable("SealedProduct");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Foil")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SealedProductContentsId")
                        .HasColumnType("int");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductContentsId");

                    b.ToTable("SealedProductCard");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SealedProductContents");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SealedProductContentsId")
                        .HasColumnType("int");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductContentsId");

                    b.ToTable("SealedProductDeck");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductOther", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SealedProductContentsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductContentsId");

                    b.ToTable("SealedProductOther");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SealedProductContentsId")
                        .HasColumnType("int");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductContentsId");

                    b.ToTable("SealedProductPack");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductSealed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SealedProductContentsId")
                        .HasColumnType("int");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductContentsId");

                    b.ToTable("SealedProductSealed");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductVariableConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SealedProductVariableConfig");
                });

            modelBuilder.Entity("CompletemtgDatabase.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseSetSize")
                        .HasColumnType("int");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardsphereSetId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeV3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFoilOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsForeignOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNonFoilOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnlineOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPaperOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPartialPreview")
                        .HasColumnType("bit");

                    b.Property<string>("KeyruneCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("McmId")
                        .HasColumnType("int");

                    b.Property<int?>("McmIdExtras")
                        .HasColumnType("int");

                    b.Property<string>("McmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TcgplayerGroupId")
                        .HasColumnType("int");

                    b.Property<string>("TokenSetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSetSize")
                        .HasColumnType("int");

                    b.Property<int>("TranslationsId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TranslationsId");

                    b.ToTable("Set");
                });

            modelBuilder.Entity("CompletemtgDatabase.SourceProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Foil")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Nonfoil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SourceProducts");
                });

            modelBuilder.Entity("CompletemtgDatabase.Translations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AncientGreek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChineseSimplified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChineseTraditional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("German")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hebrew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Italian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Japanese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Korean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phyrexian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortugueseBrazil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Russian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sanskrit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spanish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SealedProductContentsSealedProductVariableConfig", b =>
                {
                    b.Property<int>("ConfigsId")
                        .HasColumnType("int");

                    b.Property<int>("VariableId")
                        .HasColumnType("int");

                    b.HasKey("ConfigsId", "VariableId");

                    b.HasIndex("VariableId");

                    b.ToTable("SealedProductContentsSealedProductVariableConfig");
                });

            modelBuilder.Entity("CompletemtgDatabase.BoosterPack", b =>
                {
                    b.HasOne("CompletemtgDatabase.BoosterConfig", null)
                        .WithMany("Boosters")
                        .HasForeignKey("BoosterConfigId");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardSet", b =>
                {
                    b.HasOne("CompletemtgDatabase.Identifiers", "Identifiers")
                        .WithMany()
                        .HasForeignKey("IdentifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.LeadershipSkills", "LeadershipSkills")
                        .WithMany()
                        .HasForeignKey("LeadershipSkillsId");

                    b.HasOne("CompletemtgDatabase.Legalities", "Legalities")
                        .WithMany()
                        .HasForeignKey("LegalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.PurchaceUrls", "PurchaceUrls")
                        .WithMany()
                        .HasForeignKey("PurchaceUrlsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.Set", null)
                        .WithMany("Cards")
                        .HasForeignKey("SetId");

                    b.HasOne("CompletemtgDatabase.SourceProducts", "SourceProducts")
                        .WithMany()
                        .HasForeignKey("SourceProductsId");

                    b.Navigation("Identifiers");

                    b.Navigation("LeadershipSkills");

                    b.Navigation("Legalities");

                    b.Navigation("PurchaceUrls");

                    b.Navigation("SourceProducts");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardSetDeck", b =>
                {
                    b.HasOne("CompletemtgDatabase.DeckSet", null)
                        .WithMany("Commander")
                        .HasForeignKey("DeckSetId");

                    b.HasOne("CompletemtgDatabase.DeckSet", null)
                        .WithMany("MainBoard")
                        .HasForeignKey("DeckSetId1");

                    b.HasOne("CompletemtgDatabase.DeckSet", null)
                        .WithMany("SideBoard")
                        .HasForeignKey("DeckSetId2");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardToken", b =>
                {
                    b.HasOne("CompletemtgDatabase.Identifiers", "Identifiers")
                        .WithMany()
                        .HasForeignKey("IdentifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.RelatedCards", "RelatedCards")
                        .WithMany()
                        .HasForeignKey("RelatedCardsId");

                    b.Navigation("Identifiers");

                    b.Navigation("RelatedCards");
                });

            modelBuilder.Entity("CompletemtgDatabase.ForeignData", b =>
                {
                    b.HasOne("CompletemtgDatabase.CardSet", null)
                        .WithMany("ForeignData")
                        .HasForeignKey("CardSetId");

                    b.HasOne("CompletemtgDatabase.Identifiers", "Identifiers")
                        .WithMany()
                        .HasForeignKey("IdentifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProduct", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", "Contents")
                        .WithMany()
                        .HasForeignKey("ContentsId");

                    b.HasOne("CompletemtgDatabase.Identifiers", "Identifiers")
                        .WithMany()
                        .HasForeignKey("IdentifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.PurchaceUrls", "PurchaceUrls")
                        .WithMany()
                        .HasForeignKey("PurchaceUrlsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contents");

                    b.Navigation("Identifiers");

                    b.Navigation("PurchaceUrls");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductCard", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany("Card")
                        .HasForeignKey("SealedProductContentsId");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductDeck", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany("Deck")
                        .HasForeignKey("SealedProductContentsId");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductOther", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany("Other")
                        .HasForeignKey("SealedProductContentsId");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductPack", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany("Pack")
                        .HasForeignKey("SealedProductContentsId");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductSealed", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany("Sealed")
                        .HasForeignKey("SealedProductContentsId");
                });

            modelBuilder.Entity("CompletemtgDatabase.Set", b =>
                {
                    b.HasOne("CompletemtgDatabase.Translations", "Translations")
                        .WithMany()
                        .HasForeignKey("TranslationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SealedProductContentsSealedProductVariableConfig", b =>
                {
                    b.HasOne("CompletemtgDatabase.SealedProductContents", null)
                        .WithMany()
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompletemtgDatabase.SealedProductVariableConfig", null)
                        .WithMany()
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompletemtgDatabase.BoosterConfig", b =>
                {
                    b.Navigation("Boosters");
                });

            modelBuilder.Entity("CompletemtgDatabase.CardSet", b =>
                {
                    b.Navigation("ForeignData");
                });

            modelBuilder.Entity("CompletemtgDatabase.DeckSet", b =>
                {
                    b.Navigation("Commander");

                    b.Navigation("MainBoard");

                    b.Navigation("SideBoard");
                });

            modelBuilder.Entity("CompletemtgDatabase.SealedProductContents", b =>
                {
                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("Other");

                    b.Navigation("Pack");

                    b.Navigation("Sealed");
                });

            modelBuilder.Entity("CompletemtgDatabase.Set", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
